create table public.funds (
  id text primary key,
  name text not null,
  manager text not null default '',
  nisa_tsumitate boolean not null default false,
  nisa_growth boolean not null default false,
  paypay_url text not null default '',
  history_url text not null default '',
  refreshed_at timestamptz not null
);

create table public.prices (
  fund_id text not null references public.funds(id) on delete cascade,
  date date not null,
  nav double precision not null check (nav > 0),
  source_url text not null,
  primary key (fund_id, date)
);

create table public.insights (
  id bigint generated by default as identity primary key,
  fund_id text not null references public.funds(id) on delete cascade,
  publisher text not null,
  title text not null,
  summary text not null,
  source_url text not null,
  published_at timestamptz not null
);

create index idx_funds_name on public.funds(name);
create index idx_prices_fund_date on public.prices(fund_id, date);
create index idx_insights_fund_date on public.insights(fund_id, published_at desc);

-- 瀏覽器只會呼叫 Go API。啟用 RLS 可避免未來意外透過 Supabase Data API
-- 直接曝露資料表；後端則以資料庫擁有者身分連線。
alter table public.funds enable row level security;
alter table public.prices enable row level security;
alter table public.insights enable row level security;
